### ISSUE TITLE
Save button disappeared on 2.1.0

### ISSUE THREAD

**Issue by rmafort** [ScarletStudy/DGS2-3DS-Release#11]
### About your device

**Which 3DS model are you using?** (Old/New 2DS/3DS)
Old 3ds

**Which Luma3DS version are you running?** (hold SELECT on boot to check)
10.2.1

**Which 3DS firmware version are you running?** (open System Settings to check)
11.14.0-46

**Which version of our patch are you running?** (should be visible on the top right of the title screen)
2.1.0

### Your issue

Save button disappeared from lower screen

_In case of a crash, please attach the corresponding crashdump (likely the newest file in `sd:/luma/dumps/arm11/`)_

**Please describe the issue you are experiencing:**

**Comment by wabberz** [comment]
This happens when you continue from a save of the Preview. Please restart the Episode from the Chapter select menu.
