### ISSUE TITLE
A few typos found in episode 3 

### ISSUE THREAD

**Issue by SeymourSchlong** [ScarletStudy/DGS2-3DS-Release#13]
### Location

**Which Episode?**

3

**Are you running the latest version of our patch?**

Yes

### Please describe the issue

"Depending on whether it was an accident or homicide, the situation is completey different."
Here, "completely" is misspelled as "completey".

![2021-04-06_18-12-37 413_top](https://user-images.githubusercontent.com/36908123/114132268-089d1b00-98d2-11eb-8ba7-3f6da17ada84.png)

During the deduction with Madame Rosaique, before the wax arm is identified, it's called "Rozaic's Arm", as opposed to "Rosaique's Arm".

(I don't have a screenshot for this.)

**Comment by SeymourSchlong** [comment]
After finishing episode three, I noticed that often times there was inconsistencies when talking about The Professor. Sometimes characters will refer to them as "the Professor" with no capital The. While this could be intentional, it's an odd inconsistency.

**Comment by whitehelm** [comment]
I found another typo. During the Great Deduction at the wax museum, the fake arm is labelled "Rozaic's Arm" before you examine it. It should be "Rosaique's Arm".

**Comment by whitehelm** [comment]
In the second day's deduction what Sherlock calls "upside-down furniture" is labelled "Flipped Furniture". This is the choice where Sherlock complains about Naruhodou copying him, in all other instances the label has been identical to what's in Sherlock's line.
The "skylight" is also incorrectly labelled "window", this should also match for the same reason. This time it actually appears as skylight in the top screen animation when selected.

**Comment by Wendy-Youngbag** [comment]
Hi, thanks for pointing these out. I've gone through and fixed everything, except the JR labels. They've stumped us a bit as to why they're not changing, so we're going to look into it.

Thanks again! I might be back to ask for clarification on a few things.

**Comment by Wendy-Youngbag** [comment]
We got to the bottom of the JR text, and have now fixed it ready for the next patch. Thanks!
