### ISSUE TITLE
DGS2 Case 3 missing punctuation (minor spoilers)

### ISSUE THREAD

**Issue by SamuraiOndo** [ScarletStudy/DGS2-3DS-Release#14]
Location: 
During the first cross examination with Gina, Marmatch, and Gotts.
Which Episode? (1-5)
3
Are you running the latest version of our patch?
Please describe the issue
Gina ends her second statement without a period 
instead of saying "I couldn't see anythin' in the cage. After that, no one was allowed near the Crystal Tower." 
she says
"I couldn't see anythin' in the cage. After that, no one was allowed near the Crystal Tower"

**Comment by Wendy-Youngbag** [comment]
Fixed this now. Thank you, and great spot!
