### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by nameSample** [ScarletStudy/DGS2-3DS-Release#2]
I installed version 2.0.1 but the version number shown is 2.0.0. Is this a mistake on my part?
![0D519AAE-94E2-4437-8EAE-56CC9B02E2CD](https://user-images.githubusercontent.com/59262088/71485456-5883cb80-27ce-11ea-9301-b3867902efe7.jpeg)

**Comment by wabberz** [comment]
The only change in 2.0.1 was in the patcher. The game itself did not change.

**Comment by nameSample** [comment]
Oh sorry, I misunderstood it on my part.
