### ISSUE TITLE
Line missing in backlog of first case breakdown *SPOILERS*

### ISSUE THREAD

**Issue by flygongaby** [ScarletStudy/DGS2-3DS-Release#3]
Hi just wanted to report an early missing line in the breakdown of the first case breakdown. 
After Naruhodou requests to test the pen, Manemomi starts breaking down and his first line is "Oh... Oohhhghhhh...." then I remember seeing him mention "Mamemonster " in a line but when I went to see the backlog, the line isn't there and there's just a big empty space.
![81050235_762286470916971_2162216395142594560_n](https://user-images.githubusercontent.com/38236594/71536325-cd90f700-28db-11ea-9252-fe3007cb4fd1.jpg)
![80555008_3048760505151821_4510815782313132032_n](https://user-images.githubusercontent.com/38236594/71536324-cd90f700-28db-11ea-9ceb-e8729f1453e0.jpg)
Anyways keep up the great work.

**Comment by Hyarion-SS** [comment]
Unfortunately, missing lines in the backlog are an engine bug that occur even in the official English localizations of AA5 and AA6. We've looked into it from time to time, but we're not aware of any way to fix it entirely.
