### ISSUE TITLE
Various Typos and Grammar Issues - Episode 1 of DGS2

### ISSUE THREAD

**Issue by earlgreyincarnate** [ScarletStudy/DGS2-3DS-Release#4]
Here are some typos and grammar issues from episode 1.

The following lines contain the use of the pronoun "that" when it should be the pronoun "who," because the pronoun is referring to a person:

1. In Susato's introduction: "I am a legal assistant **that** aids defence attorneys in court." (This line should be "I am a legal assistant **who** aids defence attorneys in court.")
2. Haori: "I'm the one **that** should be taking responsibility. It's all my fault!"
3. Judge: "The Court requests that you confirm one thing. Are you the person **that** took this photograph?"

The following lines contain examples of stutters where the first letter doesn't produce the actual phonetic effect desired. I am not sure if you would want to change these or not, but they're a bit awkward to read:

1. Auchi: "T-That's right! You've shown us nothing of the sort, newbie!" (Should be, in my opinion, "Th-That's right!")
2. (I didn't write down who said this line and I can't remember--my apologies) "T-The culprit? You don't mean...?!"
3. (Same here) "T-Thank you, Your Honour!"
4. Haori: "Please wait! T-That photograph..."
5. Judge: "T-Then... Did he take this photograph?
6. Auchi: "S-Shut up! That incident was a political matter! Don't speak so lightly of it!" (Should be, in my opinion, "Sh-Shut up!")
7. Naruhodou (Susato): "T-Then you really stabbed her through the wall of the hut?"

Here are some other incidental things I noticed:

1. "Fountain Pen has been updated in the Court Record." -- This line, for some reason, goes outside of the text box, possibly because of a formatting issue?
2. Jezail Brett (no name given in the dialog box): "My. I must say, I haven't the faintest idea of what you're talking about." This is an extremely nitpicky thing, but the word "of" here is unnecessary and has the effect of making the idea of the line clunkier than necessary. Think "I have no idea of what you're talking about" -- the word "of" serves to make the line more complicated.
3. Auchi: "In other words, the defendant's farfetched excuse that we heard just before the recess..." -- This line, again, is extremely nitpicky. While "farfetched" as a single word is not technically incorrect, it is almost always seen with a hyphen ("far-fetched") in professional writing.
4. Mikotoba: "I dare say that this journalist would have found more success as an author." -- Small issue here, but the word is actually "daresay" with no space.
5. Mamemomi: "Let's be real. Why did you kill Mr Watson?" -- Unless Mamemomi is being intentionally disrespectful or incorrect, this should be Dr Watson, not Mr.
6. Mamemomi: "But if you think you can frame a Mamemomi model citizen with that, it's a far too wild one!" -- Again, just assuming here, but is it supposed to be another portmanteau, i.e., "Mamemodel citizen?" The phrase "Mamemomi model citizen" is still alliterative wordplay, but all other instances of this wordplay involve changing the name itself to another word, not putting it in front of the word.

Thanks! Great job with this episode. I loved playing it.

**Comment by Wendy-Youngbag** [comment]
The first issue is more a matter of style than grammatical correctness - however, I agree that the first example in particular sounds better with "who", so I'm going fix that.

For stutters, our current style is to repeat the first letter only.

And now for the specific examples:
1. Is that when you are examining in evidence by any chance? The fountain pen gets updated a lot, so I wanna make sure here!
2. Agreed, fixed.
3. Thanks - fixed.
4. Fixed (and on other occasions where this was used)
5. Fixed
6. lol, nice catch - fixed

 Thanks for these! Glad you're enjoying the episode.

**Comment by earlgreyincarnate** [comment]
>     1. Is that when you are examining in evidence by any chance? The fountain pen gets updated a lot, so I wanna make sure here!

Yes, that's correct. Thanks!
