### ISSUE TITLE
Typo, episode 2, trial 1

### ISSUE THREAD

**Issue by praabjerg** [ScarletStudy/DGS2-3DS-Release#6]
van Zieks says: "You came here to delate the defendant yourself, yes?"
I think that's supposed to be "debate"?

I still haven't finished the second episode yet, but as with the translation for the first game, I'm impressed by how good this is. Thank you so much!

**Comment by earlgreyincarnate** [comment]
Actually, delate is a word that means to testify against or denounce someone. It’s one of those great old archaic words.

**Comment by praabjerg** [comment]
Oh, you're right! I didn't look it up properly.
And it makes a lot more sense in the sentence than "debate" would.

Great work!
