### ISSUE TITLE
Episode 2 Typo (Minor Spoilers)

### ISSUE THREAD

**Issue by DatXFire** [ScarletStudy/DGS2-3DS-Release#8]
During Trial Day 2 when pressing the updated text for Juror 3 during the first closing argument Ryuunosuke says the following line:

> But I never _know_ that you could stop the flow of gas just by blowing into a pipe.

This should be _knew_ instead.

**Comment by Wendy-Youngbag** [comment]
Whoopsie! Thanks for this - fixed it ready for the next patch!
